NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@AppBundle/Controller/ApiHomeController.php"
    type:     annotation

api_user:
    resource: "@AppBundle/Controller/ApiUserController.php"
    type:     annotation